spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elmshixun
    username: root
    password: a13600582228
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
